### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by jwattyow** [daimh/sge#10]
I've got a fresh install of CentOS 8.4 and am trying to build SGE. I've cloned the latest available release and when I run 

cmake --build build -j

I get the error 

 74%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.func.c.o
[ 74%] Built target qalter
[ 74%] Built target qsub
[ 74%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.nls.c.o
**gmake[1]: *** [CMakeFiles/Makefile2:3233: source/daemons/shepherd/CMakeFiles/sge_shepherd.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....**
[ 74%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.os.c.o
[ 74%] Built target sge_shadowd
[ 74%] Linking C executable sgepasswd
[ 74%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.printf.c.o
[ 75%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.prompt.c.o
[ 75%] Linking C executable qping
[ 75%] Built target qrstat
[ 75%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.sched.c.o
[ 75%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.sig.c.o
[ 75%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.str.c.o
[ 75%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.vers.c.o
[ 75%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tc.who.c.o
[ 75%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tw.color.c.o
[ 75%] Built target sgepasswd
[ 76%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tw.comp.c.o
[ 76%] Linking C executable qsh
[ 76%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tw.help.c.o
[ 76%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tw.init.c.o
[ 76%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tw.parse.c.o
[ 76%] Built target qping
[ 76%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/tw.spell.c.o
[ 76%] Building C object source/3rdparty/qtcsh/CMakeFiles/qtcsh.dir/vms.termcap.c.o
[ 77%] Linking C executable qmake
[ 77%] Built target qsh
[ 77%] Built target qmake
[ 77%] Linking C executable qtcsh
[ 78%] Built target qtcsh
[ 78%] Linking C static library libsched.a
[ 78%] Built target sched
gmake: *** [Makefile:136: all] Error 2

Prior to running cmake I did the following:

sudo dnf group install "Development Tools"
sudo dnf --enablerepo=powertools install csh hwloc-devel openssl-devel libtirpc-devel motif-devel ncurses-devel libdb-devel pam-devel cmake
git clone https://github.com/daimh/sge.git
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/sge -DSYSTEMD=OFF

[Note: I've also tried -DSYSTEMD=ON - didn't work well at all]

How do I get this to compile? What package am I missing?

Thanks.
James.

**Comment by daimh** [comment]
I just tested it successfully on the latest CentOS 8.5 on a 8G virtual machine. Can you please make sure the two 'dnf' commands in the readme file are executed and your computer has enough memory before you test it again?

Please keep me updated, Thanks!

**Comment by jwattyow** [comment]
[root@jamesSGEvm sge]# sudo dnf group install "Development Tools"
Last metadata expiration check: 0:55:21 ago on Wed 22 Dec 2021 09:28:20 PM EST.
Dependencies resolved.
==========================================================================================================================================================================
 Package                                  Architecture                            Version                                  Repository                                Size
==========================================================================================================================================================================
Installing Groups:
 Development Tools                                                                                                                                                       

Transaction Summary
==========================================================================================================================================================================

Is this ok [y/N]: y
Complete!
[root@jamesSGEvm sge]# sudo dnf --enablerepo=powertools install csh hwloc-devel openssl-devel libtirpc-devel motif-devel ncurses-devel libdb-devel pam-devel cmake
Last metadata expiration check: 0:55:33 ago on Wed 22 Dec 2021 09:28:20 PM EST.
Package tcsh-6.20.00-13.el8.x86_64 is already installed.
Package hwloc-devel-2.2.0-3.el8.x86_64 is already installed.
Package openssl-devel-1:1.1.1k-5.el8_5.x86_64 is already installed.
Package libtirpc-devel-1.1.4-5.el8.x86_64 is already installed.
Package motif-devel-2.3.4-16.el8.x86_64 is already installed.
Package ncurses-devel-6.1-9.20180224.el8.x86_64 is already installed.
Package libdb-devel-5.3.28-42.el8_4.x86_64 is already installed.
Package pam-devel-1.3.1-15.el8.x86_64 is already installed.
Package cmake-3.20.2-4.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@jamesSGEvm sge]# 

top - 22:25:37 up  8:21,  2 users,  load average: 0.08, 0.04, 0.01
Tasks: 284 total,   2 running, 280 sleeping,   0 stopped,   2 zombie
%Cpu(s):  4.8 us,  0.8 sy,  0.0 ni, 94.0 id,  0.0 wa,  0.2 hi,  0.2 si,  0.0 st
MiB Mem :   7768.1 total,   3515.2 free,   1845.1 used,   2407.8 buff/cache
MiB Swap:   6556.0 total,   6556.0 free,      0.0 used.   5552.3 avail Mem 

Running cmake again:
...
[ 79%] Building C object source/clients/qhost/CMakeFiles/qhost.dir/qhost.c.o
/root/sge/sge/source/daemons/shepherd/shepherd.c:51:10: fatal error: systemd/sd-bus.h: No such file or directory
 #include <systemd/sd-bus.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [source/daemons/shepherd/CMakeFiles/sge_shepherd.dir/build.make:174: source/daemons/shepherd/CMakeFiles/sge_shepherd.dir/shepherd.c.o] Error 1
...

I had this working on another VM running CentOS8.4 but when my host machine rebooted I wasn't able to restart the VM (ticket opened, don't have a reply yet).

The VM I'm running was created today and I did the OS updates before trying this. It's a barebones install with just the updates and the README instructions applied.

Thanks for the quick reponse!

James.

**Comment by daimh** [comment]
Thanks! Please run 'dnf install systemd-devel' and try it again.

**Comment by jwattyow** [comment]
Awesome! Thanks! I got through the cmake process and am now running make. It's progressing fine but hasn't finished. Hoping for the best!

**Comment by jwattyow** [comment]
I've now got the daemons running for the host. Many thanks for the help!

**Comment by daimh** [comment]
@jwattyow, Thanks for the update!
